import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { PROJECTS } from '@/lib/content'

export function generateStaticParams(){return PROJECTS.map(project=>({slug:project.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const project=PROJECTS.find(p=>p.slug===slug);return project?{title:`${project.title} — 2В Сервис`,description:project.summary}:{}}

export default async function ProjectDetailPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const index=PROJECTS.findIndex(p=>p.slug===slug);const project=PROJECTS[index];if(!project)notFound();const next=PROJECTS[(index+1)%PROJECTS.length]
 return <>
  <section className="relative overflow-hidden bg-surface pb-20 pt-36 text-surface-foreground md:pb-28 md:pt-44"><div className="section-shell relative"><Link href="/projects" className="inline-flex items-center gap-2 text-sm text-surface-foreground/55 hover:text-primary"><ArrowLeft className="size-4"/> Все проекты</Link><div className="mt-12 flex flex-wrap gap-3"><span className="rounded-full bg-primary px-4 py-2 text-xs font-bold text-primary-foreground">{project.industry}</span>{project.tags.map(t=><span key={t} className="rounded-full border border-white/20 px-4 py-2 text-xs">{t}</span>)}</div><h1 className="mt-8 max-w-6xl text-balance text-5xl font-black leading-[.9] tracking-[-.07em] md:text-8xl">{project.title}</h1><div className="mt-12 flex flex-col gap-6 border-t border-white/15 pt-7 md:flex-row md:justify-between"><p className="font-bold">{project.client}</p><p className="max-w-2xl leading-relaxed text-surface-foreground/60">{project.summary}</p></div></div></section>
  {project.contractValue&&<section className="bg-accent py-10 text-accent-foreground"><div className="section-shell flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><p className="eyebrow">Контракт</p><p className="text-6xl font-black tracking-[-.07em] md:text-8xl">{project.contractValue}</p></div></section>}
  <section className="section-pad bg-background"><div className="section-shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow text-primary">Проектный контур</p><p className="mt-5 text-3xl font-black tracking-tight">{project.timeline}</p><div className="mt-8 flex flex-wrap gap-2">{project.stack.map(s=><span key={s} className="rounded-full bg-secondary px-4 py-2 text-xs font-bold">{s}</span>)}</div></div><div className="flex flex-col gap-5">{[['Задача',project.task],['Решение',project.solution],['Масштаб',project.scale],['Результат',project.result]].map(([title,text],i)=><article key={title} className={`rounded-[2rem] p-8 md:p-10 ${i===1?'bg-primary text-primary-foreground':i===3?'bg-surface text-surface-foreground':'bg-secondary'}`}><span className="text-xs font-bold uppercase tracking-widest opacity-50">0{i+1} / {title}</span><p className="mt-8 text-pretty text-xl font-medium leading-relaxed md:text-2xl">{text}</p></article>)}</div></div></section>
  <section className="bg-primary py-16 text-primary-foreground"><Link href={`/projects/${next.slug}`} className="section-shell group flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow opacity-60">Следующий проект</p><h2 className="mt-5 max-w-4xl text-3xl font-black tracking-[-.04em] md:text-5xl">{next.title}</h2></div><ArrowRight className="size-12 shrink-0 transition-transform group-hover:translate-x-2"/></Link></section>
 </>
}
