import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { PROJECTS } from '@/lib/content'

export function generateStaticParams(){return PROJECTS.map(project=>({slug:project.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const project=PROJECTS.find(p=>p.slug===slug);return project?{title:project.title,description:project.summary,alternates:{canonical:`/projects/${project.slug}`},openGraph:{type:'article',locale:'ru_RU',url:`/projects/${project.slug}`,title:`${project.title} | 2В Сервис`,description:project.summary,images:[{url:project.image,alt:`${project.clientShort}: ${project.title}`}]}}:{robots:{index:false,follow:false}}}

export default async function ProjectDetailPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const index=PROJECTS.findIndex(p=>p.slug===slug);const project=PROJECTS[index];if(!project)notFound();const next=PROJECTS[(index+1)%PROJECTS.length]
 const breadcrumbSchema={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Главная',item:'https://2bservice.ru/'},{'@type':'ListItem',position:2,name:'Проекты',item:'https://2bservice.ru/projects'},{'@type':'ListItem',position:3,name:project.title,item:`https://2bservice.ru/projects/${project.slug}`}]}
 return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema).replace(/</g,'\\u003c')}}/>
  <section className="relative overflow-hidden bg-surface pb-16 pt-28 text-surface-foreground sm:pb-20 sm:pt-32 md:pb-24 md:pt-36"><Image src={project.image} alt={`${project.clientShort}: ${project.title}`} fill priority quality={72} sizes="100vw" className="object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-surface via-surface/85 to-surface/45" aria-hidden/><div className="section-shell relative z-10"><Link href="/projects" className="inline-flex items-center gap-2 text-sm text-surface-foreground/60 transition-colors hover:text-primary"><ArrowLeft className="size-4"/> Все проекты</Link><div className="mt-10 flex flex-wrap gap-2"><span className="inline-flex items-center rounded-full border border-primary/30 bg-primary px-3.5 py-1.5 text-[11px] font-semibold text-primary-foreground">{project.industry}</span>{project.tags.map(t=><span key={t} className="inline-flex items-center rounded-full border border-white/20 bg-surface/60 px-3.5 py-1.5 text-[11px] font-semibold text-surface-foreground">{t}</span>)}</div><h1 className="display-title mt-8 max-w-5xl text-surface-foreground">{project.title}</h1><div className="mt-10 flex flex-col gap-5 border-t border-white/15 pt-6 md:flex-row md:items-start md:justify-between md:gap-12"><p className="shrink-0 font-semibold text-surface-foreground">{project.client}</p><p className="max-w-2xl text-pretty leading-relaxed text-surface-foreground/65">{project.summary}</p></div></div></section>
  {project.contractValue&&<section className="bg-accent py-10 text-accent-foreground"><div className="section-shell flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><p className="eyebrow">Контракт</p><p className="text-6xl font-black tracking-[-.07em] md:text-8xl">{project.contractValue}</p></div></section>}
  <section className="section-pad bg-background"><div className="section-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow text-primary">Проектный контур</p><p className="mt-4 max-w-sm text-2xl font-semibold leading-tight tracking-[-.03em] sm:text-3xl">{project.timeline}</p><div className="mt-7 flex flex-wrap gap-2">{project.stack.map(s=><span key={s} className="chip">{s}</span>)}</div></div><div className="flex flex-col gap-4">{[['Задача',project.task],['Решение',project.solution],['Масштаб',project.scale],['Результат',project.result]].map(([title,text],i)=><article key={title} className={`rounded-[1.5rem] p-6 sm:p-8 md:p-9 ${i===1?'bg-primary text-primary-foreground':i===3?'bg-surface text-surface-foreground':'bg-secondary'}`}><span className="eyebrow opacity-55">0{i+1} / {title}</span><p className="mt-5 max-w-3xl text-pretty text-base leading-relaxed sm:text-lg md:text-xl">{text}</p></article>)}</div></div></section>
  <section className="bg-primary py-14 text-primary-foreground sm:py-20"><Link href={`/projects/${next.slug}`} className="section-shell group flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow opacity-65">Следующий проект</p><h2 className="section-title mt-4 max-w-4xl">{next.title}</h2></div><ArrowRight className="size-9 shrink-0 transition-transform group-hover:translate-x-2"/></Link></section>
 </>
}
