import type { Metadata } from 'next'
import { ArrowUpRight } from 'lucide-react'
import { PageHero } from '@/components/page-hero'

export const metadata: Metadata = { title: 'Карьера — 2В Сервис', description: 'Работа в 2В Сервис.' }
const OPENINGS=[['Ведущий инженер по интеграции','Москва'],['Аналитик корпоративных информационных систем','Москва'],['Инженер технической поддержки enterprise-систем','Москва'],['Руководитель проектов внедрения','Москва']]
const BENEFITS=[['Масштаб задач','Системы крупнейших компаний с тысячами пользователей.'],['Полный цикл','От обследования и архитектуры до промышленного запуска.'],['Длинные проекты','Возможность по-настоящему разобраться в системе.'],['Инженерная культура','Аргументы и данные важнее должностей и шаблонов.']]
export default function CareersPage(){return <>
<PageHero eyebrow="Карьера" title="Создавайте системы, которые нельзя остановить." description="Ищем инженеров, аналитиков и руководителей проектов, которым интересны сложные задачи и реальная ответственность." />
<section className="section-pad bg-accent text-accent-foreground"><div className="section-shell"><p className="eyebrow">Почему 2В</p><div className="mt-10 grid gap-10 md:grid-cols-2">{BENEFITS.map(([title,description],i)=><article key={title} className="border-t border-accent-foreground/30 pt-6"><span className="text-6xl font-black text-primary">0{i+1}</span><h2 className="mt-10 text-3xl font-black tracking-tight">{title}</h2><p className="mt-3 max-w-md opacity-70">{description}</p></article>)}</div></div></section>
<section className="section-pad bg-background"><div className="section-shell"><p className="eyebrow text-primary">Открытые позиции</p><div className="mt-10 flex flex-col">{OPENINGS.map(([title,location],i)=><a key={title} href={`mailto:hr@2v-service.ru?subject=${encodeURIComponent(`Отклик: ${title}`)}`} className="group flex items-center justify-between gap-6 border-t border-border py-7 last:border-b"><div className="flex items-center gap-6"><span className="font-mono text-xs text-primary">0{i+1}</span><div><h2 className="text-xl font-bold md:text-3xl">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{location} · Полная занятость</p></div></div><ArrowUpRight className="size-6 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></a>)}</div><p className="mt-10 text-muted-foreground">Не нашли позицию? Напишите на <a href="mailto:hr@2v-service.ru" className="font-bold text-foreground underline">hr@2v-service.ru</a></p></div></section>
</>}
