import type { Metadata } from 'next'
import { Check } from 'lucide-react'
import { LeadForm } from '@/components/lead-form'
import { CareersIntro } from '@/components/editorial/page-intros'

export const metadata: Metadata = { title: 'Карьера — 2В Сервис', description: 'Работа в команде 2В Сервис: открытый отклик для инженеров, аналитиков и руководителей проектов.' }
const DIRECTIONS=['Инфраструктура и системное администрирование','Корпоративные информационные системы','Интеграция и миграция данных','Проектное управление и аналитика','Техническая поддержка enterprise-систем']
const PRINCIPLES=[['Сложные задачи','Проекты, где нужно понимать систему целиком, а не закрывать изолированный тикет.'],['Полный цикл','Участие от обследования и архитектуры до запуска и промышленной поддержки.'],['Инженерная среда','Решения обсуждаются на языке фактов, рисков и измеримых требований.'],['Длинная дистанция','Можно увидеть, как система развивается после запуска и влияет на бизнес заказчика.']]

export default function CareersPage(){return <>
<CareersIntro />
<section className="section-pad bg-background"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-primary">Сейчас</p><h2 className="section-title mt-5">Публичного списка вакансий нет.</h2><p className="mt-6 max-w-md leading-relaxed text-muted-foreground">Мы не будем показывать вымышленные позиции. Но принимаем открытые отклики и возвращаемся, когда появляется задача под ваш профиль.</p></div><div className="rounded-[2rem] bg-secondary p-7 md:p-10"><p className="text-sm font-bold">Особенно интересны специалисты по направлениям:</p><ul className="mt-7 flex flex-col">{DIRECTIONS.map(item=><li key={item} className="flex gap-3 border-t border-border py-4 text-lg font-medium last:border-b"><Check className="mt-1 size-4 shrink-0 text-primary"/>{item}</li>)}</ul></div></div></section>
<section className="section-pad bg-surface text-surface-foreground"><div className="section-shell"><p className="eyebrow text-primary">Среда работы</p><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] bg-white/15 md:grid-cols-2">{PRINCIPLES.map(([title,text],i)=><article key={title} className="min-h-64 bg-surface p-8"><span className="font-mono text-xs text-primary">0{i+1}</span><h2 className="mt-14 text-3xl font-bold tracking-tight">{title}</h2><p className="mt-4 max-w-lg leading-relaxed text-surface-foreground/55">{text}</p></article>)}</div></div></section>
<section className="section-pad bg-background"><div className="section-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-primary">Открытый отклик</p><h2 className="section-title mt-5">Расскажите, чем вы сильны.</h2><p className="mt-5 max-w-md leading-relaxed text-muted-foreground">Укажите специализацию, ключевой опыт и ссылку на резюме. Отклик попадёт напрямую команде.</p></div><LeadForm source="career" heading="Познакомимся до появления подходящей позиции" messageLabel="Опыт и специализация" messagePlaceholder="Расскажите о ключевом опыте и добавьте ссылку на резюме" submitLabel="Отправить отклик"/></div></section>
</>}
