import type { Metadata } from 'next'
import { PageHero } from '@/components/page-hero'
import { STATS } from '@/lib/content'

export const metadata: Metadata = { title: 'О компании — 2В Сервис', description: '2В Сервис — единый ИТ-партнёр крупных организаций.' }
const PRINCIPLES=[['Отвечаем за результат','Ведём проект до промышленной эксплуатации и отвечаем за работу системы.'],['Работаем на длинной дистанции','Глубоко понимаем процессы и развиваем решения вместе с заказчиком.'],['Понимаем масштаб enterprise','Работаем с системами, где тысячи пользователей и простой недопустим.'],['Инженерный подход','Решения основаны на архитектуре, процессах и измеримых требованиях.']]
export default function AboutPage(){return <>
<PageHero eyebrow="О компании" title="Рядом, когда система становится бизнесом." description="Российская ИТ-компания с 15-летним опытом: создаём и обслуживаем инфраструктуру, внедряем корпоративные системы и поддерживаем объекты по всей стране." />
<section className="section-pad bg-background"><div className="section-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-primary">С 2010 года</p><h2 className="section-title mt-5">Работаем там, где ошибка стоит дорого.</h2></div><div className="rounded-[2rem] bg-secondary p-8 md:p-12"><p className="text-lead">Проектируем, внедряем и поддерживаем ИТ-среду крупных организаций.</p><p className="mt-8 max-w-2xl leading-relaxed text-muted-foreground">Архитекторы, инженеры, аналитики и специалисты поддержки работают как один центр ответственности — не перекладывая проблему между подрядчиками.</p></div></div></section>
<section className="overflow-hidden bg-primary py-8 text-primary-foreground"><div className="marquee flex gap-16 whitespace-nowrap text-7xl font-black tracking-[-.07em] md:text-9xl">{[...STATS,...STATS].map((s,i)=><span key={`${s.label}-${i}`}>{s.value} <small className="text-xl font-medium opacity-60">{s.label}</small></span>)}</div></section>
<section className="section-pad bg-surface text-surface-foreground"><div className="section-shell"><p className="eyebrow text-primary">Принципы</p><div className="mt-10 grid gap-5 md:grid-cols-2">{PRINCIPLES.map(([title,description],i)=><article key={title} className={`min-h-64 rounded-[2rem] p-8 ${i===2?'bg-accent text-accent-foreground':'border border-white/15'}`}><span className="text-5xl font-black opacity-20">0{i+1}</span><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-3 max-w-lg leading-relaxed opacity-65">{description}</p></article>)}</div></div></section>
</>}
