import type { Metadata } from 'next'
import { PageHero } from '@/components/page-hero'
import { TECH_AREAS, INDUSTRIES, PROCESS_STEPS } from '@/lib/content'

export const metadata: Metadata = { title: 'Технологии и экспертиза — 2В Сервис', description: 'Технологическая экспертиза 2В Сервис.' }
export default function TechnologiesPage(){return <>
<PageHero eyebrow="Технологии" title="Архитектура должна выдерживать реальность." description="Проектируем технологическую основу, которая сохраняет устойчивость при росте, изменениях и критичных нагрузках." />
<section className="section-pad bg-background"><div className="section-shell"><p className="eyebrow text-primary">Технологический стек</p><div className="mt-10 grid auto-rows-[14rem] gap-4 md:grid-cols-3">{TECH_AREAS.map((area,i)=><article key={area.title} className={`flex flex-col justify-between rounded-[2rem] p-7 ${i===0||i===5?'bg-primary text-primary-foreground md:col-span-2':i===3?'bg-accent text-accent-foreground':'bg-secondary'}`}><span className="font-mono text-xs opacity-50">T / 0{i+1}</span><div><h2 className="text-2xl font-bold tracking-tight">{area.title}</h2><p className="mt-3 max-w-lg text-sm leading-relaxed opacity-70">{area.description}</p></div></article>)}</div></div></section>
<section className="section-pad overflow-hidden bg-surface text-surface-foreground"><div className="section-shell"><p className="eyebrow text-primary">Процесс</p><h2 className="section-title mt-5 max-w-4xl">Восемь шагов. Один управляемый контур.</h2><div className="mt-14 flex gap-4 overflow-x-auto pb-4">{PROCESS_STEPS.map((step,i)=><article key={step.title} className="min-h-72 min-w-64 rounded-[2rem] border border-white/15 p-7"><span className="text-6xl font-black text-primary">{String(i+1).padStart(2,'0')}</span><h3 className="mt-12 text-xl font-bold">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-surface-foreground/55">{step.description}</p></article>)}</div></div></section>
<section className="section-pad bg-accent text-accent-foreground"><div className="section-shell"><p className="eyebrow">Отрасли</p><div className="mt-10 grid gap-10 md:grid-cols-2">{INDUSTRIES.map((industry,i)=><article key={industry.title} className="border-t border-accent-foreground/30 pt-6"><span className="font-mono text-xs opacity-50">0{i+1}</span><h3 className="mt-8 text-4xl font-black tracking-[-0.05em] md:text-5xl">{industry.title}</h3><p className="mt-4 max-w-lg leading-relaxed opacity-70">{industry.description}</p></article>)}</div></div></section>
</>}
