import type { Metadata } from 'next'
import { PageHero } from '@/components/page-hero'
import { TECH_AREAS, INDUSTRIES } from '@/lib/content'

export const metadata: Metadata = { title: 'Технологии и экспертиза — 2В Сервис', description: 'Архитектура, интеграция, данные, безопасность и эксплуатация enterprise-систем.' }
const LAYERS=[['Процессы','Документооборот, BPM и корпоративные порталы'],['Данные','Миграция, НСИ и контролируемый обмен'],['Интеграция','API, шины и связь с действующим ландшафтом'],['Эксплуатация','Отказоустойчивость, безопасность и поддержка']]

export default function TechnologiesPage(){return <>
<PageHero eyebrow="Технологии" title="Не коллекция продуктов. Цельная архитектура." description="Выбираем технологии от требований к процессам, данным, нагрузке и эксплуатации — а не наоборот." />
<section className="section-pad bg-background"><div className="section-shell"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-primary">Архитектурные слои</p><h2 className="section-title mt-5">Каждый слой работает на общий результат.</h2></div><div className="grid gap-4 sm:grid-cols-2">{LAYERS.map(([title,text],i)=><article key={title} className={`min-h-56 rounded-[2rem] p-7 ${i===0?'bg-primary text-primary-foreground':i===3?'bg-surface text-surface-foreground':'bg-secondary'}`}><span className="font-mono text-xs opacity-50">L / 0{i+1}</span><h3 className="mt-14 text-3xl font-bold tracking-tight">{title}</h3><p className="mt-3 max-w-sm text-sm leading-relaxed opacity-65">{text}</p></article>)}</div></div></div></section>
<section className="section-pad bg-secondary"><div className="section-shell"><p className="eyebrow text-primary">Компетенции внутри слоёв</p><div className="mt-10 flex flex-col">{TECH_AREAS.map((area,i)=><article key={area.title} className="grid gap-3 border-t border-border py-6 last:border-b md:grid-cols-[5rem_.8fr_1.2fr] md:items-start"><span className="font-mono text-xs text-muted-foreground">T / {String(i+1).padStart(2,'0')}</span><h2 className="text-xl font-bold tracking-tight md:text-2xl">{area.title}</h2><p className="max-w-2xl text-sm leading-relaxed text-muted-foreground">{area.description}</p></article>)}</div></div></section>
<section className="section-pad bg-surface text-surface-foreground"><div className="section-shell"><div className="flex flex-col gap-5 border-b border-white/15 pb-10 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow text-primary">Отраслевая практика</p><h2 className="section-title mt-5">Архитектура учитывает цену остановки.</h2></div><p className="max-w-md leading-relaxed text-surface-foreground/55">Технологические решения проверяем не презентацией, а условиями реальной эксплуатации.</p></div><div className="grid gap-px bg-white/15 md:grid-cols-2">{INDUSTRIES.map((industry,i)=><article key={industry.title} className="bg-surface py-9 md:p-9"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-7 text-3xl font-bold tracking-tight">{industry.title}</h3><p className="mt-4 max-w-lg leading-relaxed text-surface-foreground/55">{industry.description}</p></article>)}</div></div></section>
</>}
