import Image from 'next/image'
import type { ReactNode } from 'react'

function Intro({ children, scene }: { children: ReactNode; scene: ReactNode }) {
  return <section className="relative overflow-hidden bg-surface pb-14 pt-28 text-surface-foreground sm:pt-32 md:min-h-[42rem] md:pb-20 md:pt-40"><div className="route-grid absolute inset-0 opacity-40"/><div className="section-shell relative grid items-center gap-10 lg:grid-cols-[.92fr_1.08fr]">{children}<div className="min-h-72 lg:min-h-[28rem]">{scene}</div></div></section>
}
function Copy({ code,title,accent,body }:{code:string;title:string;accent:string;body:string}) { return <div className="relative z-10"><p className="eyebrow text-primary">{code}</p><h1 data-reveal="clip" className="mt-7 text-balance text-5xl font-semibold leading-[.88] tracking-[-.065em] sm:text-6xl md:text-7xl">{title}<span className="block text-primary">{accent}</span></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-surface-foreground/60 sm:text-lg">{body}</p></div> }
const Dot=({className}:{className:string})=><span className={`absolute size-3 rounded-full bg-accent shadow-[0_0_0_8px_color-mix(in_oklab,var(--accent)_18%,transparent)] ${className}`}/>

export function ServicesIntro(){return <Intro scene={<div className="relative h-full min-h-72"><div className="absolute inset-y-8 left-1/2 w-px bg-white/15"/><div className="absolute left-0 right-0 top-1/2 h-px bg-white/15"/><div className="absolute left-[8%] top-[12%] rounded-[2rem] bg-primary p-6 shadow-2xl"><p className="eyebrow opacity-55">Контур 01</p><p className="mt-12 text-3xl font-bold">Инфраструктура</p></div><div className="absolute bottom-[6%] right-[2%] rounded-[2rem] bg-accent p-6 text-accent-foreground shadow-2xl"><p className="eyebrow opacity-55">Контур 09</p><p className="mt-12 text-3xl font-bold">Поддержка 24/7</p></div><Dot className="left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"/></div>}><Copy code="Решения / единый контур" title="Система работает" accent="как одно целое." body="Проектируем, запускаем и поддерживаем весь ИТ-ландшафт — без разрывов между подрядчиками."/></Intro>}

export function ProjectsIntro(){return <Intro scene={<div className="relative h-full min-h-72 overflow-hidden rounded-[2rem]"><Image src="/images/project-integration.png" alt="Инженер проверяет инфраструктуру проекта" fill priority className="object-cover opacity-75"/><div className="absolute inset-0 bg-gradient-to-t from-surface via-transparent to-transparent"/><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between border-t border-white/30 pt-4"><strong>CASE / 05</strong><span className="font-mono text-xs text-white/55">2010—2026</span></div></div>}><Copy code="Проекты / карта результата" title="Не обещания." accent="Работающие системы." body="Разбираем проекты по фактам: задача, архитектура, запуск и результат в эксплуатации."/></Intro>}

export function TechnologiesIntro(){const principles=[['01','Процессы','Сначала описываем реальную работу бизнеса.'],['02','Данные','Определяем владельцев, качество и движение данных.'],['03','Интеграция','Связываем новый контур с действующим ландшафтом.'],['04','Эксплуатация','Проектируем обновления, контроль и поддержку заранее.']];return <section className="bg-surface pt-28 text-surface-foreground sm:pt-32 md:pt-40"><div className="section-shell"><div className="border-b border-white/15 pb-10 md:pb-14"><div className="flex items-center justify-between gap-6"><p className="eyebrow text-accent">Технологии / принципы выбора</p><p className="hidden font-mono text-xs text-surface-foreground/40 sm:block">STACK IS A CONSEQUENCE</p></div><h1 data-reveal="clip" className="mt-8 max-w-6xl text-balance text-5xl font-semibold leading-[.9] tracking-[-.065em] sm:text-7xl lg:text-8xl">Не продаём стек.<br/><span className="text-primary">Собираем систему.</span></h1><div className="mt-8 flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><p className="max-w-2xl text-base leading-relaxed text-surface-foreground/60 sm:text-lg">Технология появляется в проекте только тогда, когда отвечает требованиям процессов, данных, интеграции и дальнейшей эксплуатации.</p><p className="font-mono text-xs text-surface-foreground/40">ARCH / 2010—2026</p></div></div><div className="grid md:grid-cols-4">{principles.map(([number,title,text],index)=><article key={title} className={`flex min-h-64 flex-col justify-between border-white/15 py-7 md:min-h-80 md:border-r md:px-6 md:py-8 md:first:pl-0 md:last:border-r-0 md:last:pr-0 ${index<principles.length-1?'border-b md:border-b-0':''} ${index===2?'bg-accent px-6 text-accent-foreground md:-mt-px':''}`}><span className="font-mono text-xs opacity-50">{number} / 04</span><div><h2 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h2><p className="mt-4 max-w-xs text-sm leading-relaxed opacity-60">{text}</p></div></article>)}</div></div></section>}

export function ClientsIntro(){return <Intro scene={<div className="relative h-full min-h-72"><div className="absolute inset-x-0 top-12 h-px bg-white/20"/><div className="absolute inset-x-0 top-1/2 h-px bg-white/20"/><div className="absolute inset-x-0 bottom-12 h-px bg-white/20"/><div className="absolute left-[12%] top-12 h-[calc(50%-3rem)] w-px bg-primary"/><div className="absolute right-[18%] top-1/2 h-[calc(50%-3rem)] w-px bg-accent"/><Dot className="left-[12%] top-10"/><Dot className="right-[18%] top-[calc(50%-6px)]"/><p className="absolute left-[18%] top-20 text-3xl font-bold">АВИАЦИЯ</p><p className="absolute right-[4%] top-[55%] text-3xl font-bold">TRAVELTECH</p><p className="absolute bottom-2 left-[34%] font-mono text-xs text-white/45">длинная дистанция / 15 лет</p></div>}><Copy code="Клиенты / линия доверия" title="Критичные системы." accent="Долгие отношения." body="Работаем там, где устойчивость ИТ напрямую определяет непрерывность бизнеса."/></Intro>}

export function CompetenciesIntro(){return <Intro scene={<div className="grid h-full min-h-72 grid-cols-2 gap-3"><div className="flex flex-col justify-between rounded-[2rem] border border-white/15 p-6"><span className="font-mono text-xs text-primary">FIELD / 01</span><strong className="text-2xl">Инженерные системы</strong></div><div className="flex flex-col justify-between rounded-[2rem] bg-primary p-6"><span className="font-mono text-xs opacity-55">FIELD / 02</span><strong className="text-2xl">Оснащение офиса</strong></div><div className="col-span-2 flex items-center justify-between rounded-[2rem] bg-accent p-6 text-accent-foreground"><strong className="text-2xl">Один проект — меньше стыков</strong><span className="text-5xl">+</span></div></div>}><Copy code="Компетенции / вокруг ядра" title="Закрываем" accent="смежный контур." body="Подключаем дополнительные работы, когда это снижает риски и ускоряет основной ИТ-проект."/></Intro>}

export function AboutIntro(){return <Intro scene={<div className="relative h-full min-h-72 overflow-hidden rounded-[2rem]"><Image src="/images/editorial-about.png" alt="Чертежи и современная ИТ-инфраструктура" fill priority className="object-cover opacity-75"/><div className="absolute inset-0 bg-gradient-to-t from-surface via-transparent to-transparent"/><div className="absolute bottom-6 left-6"><p className="font-mono text-xs text-primary">2010 → 2026</p><p className="mt-2 text-2xl font-bold">Опыт остаётся внутри системы</p></div></div>}><Copy code="Компания / непрерывность" title="15 лет" accent="внутри систем." body="Объединяем инфраструктуру, корпоративные решения, интеграцию и поддержку в одном центре ответственности."/></Intro>}

export function CareersIntro(){return <Intro scene={<div className="relative h-full min-h-72 overflow-hidden rounded-[2rem]"><Image src="/images/editorial-careers.png" alt="Команда инженеров обсуждает техническую схему" fill priority className="object-cover opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-surface via-transparent to-transparent"/><p className="absolute bottom-6 left-6 right-6 text-balance text-xl font-bold">Понимать систему целиком, а не просто закрывать тикеты.</p></div>}><Copy code="Карьера / инженерная среда" title="Сложные задачи." accent="Видимый результат." body="Работа от обследования и архитектуры до запуска и промышленной поддержки."/></Intro>}

export function ContactsIntro(){return <Intro scene={<div className="relative grid h-full min-h-72 place-items-center"><div className="absolute size-72 rounded-full border border-white/15"/><div className="absolute size-52 rounded-full border border-primary/50"/><div className="absolute size-32 rounded-full border border-white/20"/><div className="locator-pulse size-5 rounded-full bg-accent"/><span className="absolute bottom-5 font-mono text-xs text-white/45">55.747° N / 37.537° E</span></div>}><Copy code="Контакты / точка входа" title="Начнём" accent="с вашей задачи." body="Коротко опишите контекст — вернёмся с вопросами и понятным следующим шагом."/></Intro>}
