import type { ReactNode } from 'react'

function Intro({ children, scene }: { children: ReactNode; scene?: ReactNode }) {
  return <section className="relative max-h-[700px] overflow-hidden bg-surface pb-10 pt-24 text-surface-foreground sm:pb-14 sm:pt-28 md:pb-16 md:pt-32"><div className="route-grid absolute inset-0 opacity-25 sm:opacity-40"/><div className={`section-shell relative grid items-center gap-7 sm:gap-10 ${scene ? 'lg:grid-cols-[.92fr_1.08fr]' : ''}`}>{children}{scene ? <div className="min-h-52 sm:min-h-64 lg:min-h-[25rem]">{scene}</div> : null}</div></section>
}
function Copy({ code,title,accent,body }:{code:string;title:string;accent:string;body:string}) { return <div className="relative z-10"><p className="eyebrow text-primary">{code}</p><h1 data-reveal="clip" className="mt-6 text-balance text-[clamp(2.75rem,13vw,3.5rem)] font-semibold leading-[.9] tracking-[-.06em] sm:mt-7 sm:text-6xl md:text-7xl">{title}{' '}<span className="block text-primary">{accent}</span></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-surface-foreground/60 sm:text-lg">{body}</p></div> }
const Dot=({className}:{className:string})=><span className={`absolute size-3 rounded-full bg-accent shadow-[0_0_0_8px_color-mix(in_oklab,var(--accent)_18%,transparent)] ${className}`}/>

export function ServicesIntro(){return <Intro scene={<div className="relative grid h-full min-h-0 grid-cols-2 gap-3 lg:block lg:min-h-72"><div className="hidden lg:absolute lg:inset-y-8 lg:left-1/2 lg:block lg:w-px lg:bg-white/15"/><div className="hidden lg:absolute lg:left-0 lg:right-0 lg:top-1/2 lg:block lg:h-px lg:bg-white/15"/><div className="flex min-w-0 flex-col justify-between rounded-[1.5rem] bg-primary p-4 shadow-xl sm:p-6 lg:absolute lg:left-[8%] lg:top-[12%] lg:block lg:rounded-[2rem] lg:shadow-2xl"><p className="eyebrow opacity-55">Контур 01</p><p className="mt-8 text-pretty text-[clamp(.75rem,3.6vw,1.125rem)] font-bold [overflow-wrap:normal] [word-break:keep-all] sm:text-2xl lg:mt-12 lg:text-3xl">Инфраструктура</p></div><div className="flex min-w-0 flex-col justify-between rounded-[1.5rem] bg-accent p-4 text-accent-foreground shadow-xl sm:p-6 lg:absolute lg:bottom-[6%] lg:right-[2%] lg:block lg:rounded-[2rem] lg:shadow-2xl"><p className="eyebrow opacity-55">Контур 09</p><p className="mt-8 text-pretty text-lg font-bold sm:text-2xl lg:mt-12 lg:text-3xl">Поддержка 24/7</p></div><Dot className="hidden lg:left-1/2 lg:top-1/2 lg:block lg:-translate-x-1/2 lg:-translate-y-1/2"/></div>}><Copy code="Решения / единый контур" title="Система работает" accent="как одно целое" body="Проектируем, запускаем и поддерживаем весь ИТ-ландшафт — без разрывов между подрядчиками."/></Intro>}

export function ProjectsIntro(){return <Intro scene={<div className="flex h-full min-h-72 flex-col justify-between rounded-[2rem] border border-white/15 bg-white/[.03] p-6 sm:p-8"><div className="flex items-start justify-between gap-6 border-b border-white/15 pb-6"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Кейсы</p><p className="mt-3 text-5xl font-semibold tracking-[-.06em] sm:text-6xl">05</p></div><p className="max-w-36 text-right text-sm leading-relaxed text-white/55">Проекты, которые продолжают работать после запуска</p></div><div className="grid grid-cols-3 gap-3 pt-6 text-xs text-white/55"><div><span className="mb-3 block size-2 rounded-full bg-primary"/><p>Задача</p></div><div><span className="mb-3 block size-2 rounded-full bg-primary"/><p>Решение</p></div><div><span className="mb-3 block size-2 rounded-full bg-accent"/><p>Результат</p></div></div></div>}><Copy code="Проекты / карта результата" title="Не обещания" accent="Внедрённые решения" body="Разбираем проекты по фактам: задача, архитектура, запуск и результат в эксплуатации."/></Intro>}

export function TechnologiesIntro(){const stack=[['Вычисления','Серверы · Виртуализация'],['Хранение','СХД · Backup'],['Сеть','LAN · Wi-Fi · Периметр'],['Контроль','Мониторинг · SLA']];return <section className="overflow-hidden bg-background pt-28 text-foreground sm:pt-32 md:pt-40"><div className="section-shell"><div className="grid border-b border-border lg:grid-cols-[1fr_1.15fr]"><div className="flex flex-col justify-between border-border pb-10 lg:min-h-[34rem] lg:border-r lg:pb-14 lg:pr-14"><div><p className="eyebrow text-primary">Технологии / рабочая архитектура</p><h1 data-reveal="clip" className="mt-6 max-w-2xl text-balance text-[clamp(2.75rem,13vw,3.5rem)] font-semibold leading-[.92] tracking-[-.06em] sm:mt-8 sm:text-6xl md:text-7xl">Технологии не живут отдельно</h1></div><div className="mt-12 flex items-end justify-between gap-6"><p className="max-w-lg text-base leading-relaxed text-muted-foreground sm:text-lg">Мы собираем их вокруг конкретного процесса — с понятными связями, владельцами и правилами эксплуатации.</p><span className="hidden size-4 shrink-0 rounded-full bg-accent shadow-[0_0_0_12px_color-mix(in_oklab,var(--accent)_16%,transparent)] sm:block"/></div></div><div className="py-8 lg:pl-14"><div className="flex items-center justify-between gap-4 border-b border-border pb-5"><span className="font-mono text-xs text-muted-foreground">СИСТЕМНЫЙ КОНТУР</span><span className="font-mono text-xs text-primary">LIVE / 04</span></div><div className="flex flex-col">{stack.map(([title,tools],index)=><div key={title} className="group grid grid-cols-[3rem_1fr] items-center border-b border-border py-5 sm:grid-cols-[4rem_1fr_auto] sm:py-6"><span className="font-mono text-xs text-muted-foreground">0{index+1}</span><strong className="text-xl tracking-tight sm:text-2xl">{title}</strong><span className="col-start-2 mt-2 font-mono text-xs text-muted-foreground sm:col-start-auto sm:mt-0">{tools}</span></div>)}</div><div className="mt-7 bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex items-start justify-between gap-8"><div><p className="font-mono text-xs opacity-60">ПРИНЦИП ВЫБОРА</p><p className="mt-8 max-w-md text-2xl font-semibold leading-tight sm:text-3xl">Сначала требования к системе. Затем продукты и вендоры.</p></div><span className="font-mono text-xs opacity-60">2В / ARCH</span></div></div></div></div></div></section>}

export function ClientsIntro(){return <Intro><Copy code="Клиенты / линия доверия" title="Критичные системы" accent="Долгие отношения" body="Работаем там, где устойчивость ИТ напрямую определяет непрерывность бизнеса."/></Intro>}

export function CompetenciesIntro(){return <Intro scene={<div className="grid h-full min-h-72 grid-cols-2 gap-3"><div className="flex flex-col justify-between rounded-[2rem] border border-white/15 p-6"><span className="font-mono text-xs text-primary">FIELD / 01</span><strong className="text-2xl">Инженерные системы</strong></div><div className="flex flex-col justify-between rounded-[2rem] bg-primary p-6"><span className="font-mono text-xs opacity-55">FIELD / 02</span><strong className="text-2xl">Оснащение офиса</strong></div><div className="col-span-2 flex items-center justify-between rounded-[2rem] bg-accent p-6 text-accent-foreground"><strong className="text-2xl">Один проект — меньше стыков</strong><span className="text-5xl">+</span></div></div>}><Copy code="Компетенции / вокруг ядра" title="Закрываем" accent="смежный контур" body="Подключаем дополнительные работы, когда это снижает риски и ускоряет основной ИТ-проект."/></Intro>}

export function AboutIntro(){return <Intro><Copy code="Компания / непрерывность" title="15 лет" accent="внутри систем" body="Объединяем инфраструктуру, корпоративные решения, интеграцию и поддержку в одном центре ответственности."/><div className="relative z-10 mt-10 inline-flex items-center gap-4 rounded-full border border-white/15 bg-white/[.04] py-3 pl-5 pr-6"><span className="font-mono text-xs text-primary">2010 → 2026</span><span className="h-4 w-px bg-white/20"/><span className="text-sm font-semibold text-surface-foreground/80">Опыт остается внутри системы</span></div></Intro>}

export function CareersIntro(){return <Intro><Copy code="Карьера / инженерная среда" title="Сложные задачи" accent="Видимый результат" body="Работа от обследования и архитектуры до запуска и промышленной поддержки."/><p className="relative z-10 mt-10 max-w-xl text-pretty border-l-2 border-primary pl-5 text-lg font-medium leading-snug text-surface-foreground/70">Понимать систему целиком, а не просто закрывать тикеты.</p></Intro>}

export function ContactsIntro(){return <Intro scene={<div className="relative grid h-full min-h-72 place-items-center"><div className="absolute size-72 rounded-full border border-white/15"/><div className="absolute size-52 rounded-full border border-primary/50"/><div className="absolute size-32 rounded-full border border-white/20"/><div className="locator-pulse size-5 rounded-full bg-accent"/><span className="absolute bottom-5 font-mono text-xs text-white/45">55.747° N / 37.537° E</span></div>}><Copy code="Контакты / точка входа" title="Начнем" accent="с вашей задачи" body="Коротко опишите контекст — вернемся с вопросами и понятным следующим шагом."/></Intro>}
